// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OsiguSDK.SpecificationTests.Settlements.Calculation
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Validate the calculatios of Settements")]
    public partial class ValidateTheCalculatiosOfSettementsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ValidateTheCalculatiosOfSettlements.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Validate the calculatios of Settements", "\tIn order to validate the calculation of Settlements\r\n\tI want to create settlemen" +
                    "ts \r\n\tAnd validate the correct calculation for each one", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate settlement calculation")]
        [NUnit.Framework.TestCaseAttribute("1", "1", "LESS_THAN_2800", "IsNotRetainingAgent", "Cashout", new string[0])]
        [NUnit.Framework.TestCaseAttribute("6", "3", "GREATER_THAN_33600", "IsNotRetainingAgent", "Cashout", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7", "1", "LESS_THAN_2800", "IsNotRetainingAgent", "Normal", new string[0])]
        [NUnit.Framework.TestCaseAttribute("12", "3", "GREATER_THAN_33600", "IsNotRetainingAgent", "Normal", new string[0])]
        [NUnit.Framework.TestCaseAttribute("13", "1", "LESS_THAN_2800", "IsRetainingAgent", "Cashout", new string[0])]
        [NUnit.Framework.TestCaseAttribute("18", "3", "GREATER_THAN_33600", "IsRetainingAgent", "Cashout", new string[0])]
        [NUnit.Framework.TestCaseAttribute("19", "1", "LESS_THAN_2800", "IsRetainingAgent", "Normal", new string[0])]
        [NUnit.Framework.TestCaseAttribute("24", "3", "GREATER_THAN_33600", "IsRetainingAgent", "Normal", new string[0])]
        public virtual void ValidateSettlementCalculation(string testId, string numberOfClaims, string claimAmount, string providerType, string settlementType, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate settlement calculation", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have the settlement client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And(string.Format("I have {0} claims with amount \'{1}\'", numberOfClaims, claimAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
